const AuthController = require('../controllers/AuthController')
const CourseController = require('../controllers/CourseController')
const LanguageController = require('../controllers/LanguageController')
const UserController = require('../controllers/UserController')
const router = require('express').Router()

router.post('/login', AuthController.login) 
router.post('/register', AuthController.register)
router.get(`/user`, UserController.getAllUsers)
router.get(`/user/:id`, UserController.getUserById)
router.post(`/user/:id/profile`, UserController.createUserProfile)
router.get(`/user/:id/profile`, UserController.getUserProfile)
router.put(`/user/:id/profile`, UserController.updateUserProfile)
router.post(`/user/:id/progress`, UserController.createUserProgress)
router.get(`/user/:id/progress`, UserController.getUserProgress)
router.delete(`/user/:id`, UserController.deleteUser)
router.get(`/user/:id/progress/:courseId`, UserController.getUserProgress)
router.put(`/user/:id/progress/:courseId`, UserController.updateUserProgress)
router.get(`/languages`, LanguageController.getAllLanguages)
router.get(`/languages/:id`, LanguageController.getLanguageById)
router.post(`/languages`, LanguageController.createLanguage)
router.delete(`/languages/:id`, LanguageController.deleteLanguage)
router.get(`/courses`, CourseController.getAllCourses)
router.get(`/courses/:id`, CourseController.getCourseById)
router.post(`/courses`, CourseController.createCourse)
router.put(`/courses/:id`, CourseController.updateCourse)
router.delete(`/courses/:id`, CourseController.deleteCourse)
module.exports = router